### PR TITLE
fix(ui): Role Tab Member Status and Role Naming Issues (#1097)

### LINKED ISSUE #1097: PLATFORM: Role Tab UI fix
# Issues-
### suggested fix:
   - Render the avatar dimmed for invited members.
   - Change the date label from “Joined” to “Invited” when appropriate.
Image

## 2) Workspace and Role authorities share identical names
- `Read Workspace` and `Read Workspace Role` both appear as `Read Workspace` , have a complete name like `Read Workspace Roles` or `Read Roles`
- Additionally, the 2×N grid feels cramped. Maybe `w-fit` is better choice

Image

Image

### PR DESCRIPTION
**Pull request by PrasunShrivastav**
## Description

1 . The backend api gave invitationAccepted data but the fronted did not used it so I exposed it to the frontend and used it to differentiate if a member is joined or invited  <br />
2. The issue of  both role Read Workspace and Read Workspace Role being displayed as Read Workspace because the function used to display it only considered first two word fixed it now it displays full role name <br />

Fixes #1097 

## Dependencies

No new dependencies added

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

@rajdip-b for helping me setup the codebase locally 

## Screenshots of relevant screens

image

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Fix member status display to show invited vs joined

- Correct role name formatting for multi-word authorities

- Add invitation acceptance status to backend response

- Improve UI styling for authority tiles and member avatars

___

### Diagram Walkthrough

```mermaid
flowchart LR
  API["Backend API"] -- "Add invitationAccepted field" --> Schema["Schema Update"]
  Schema -- "Include invitation status" --> Frontend["Frontend Component"]
  Frontend -- "Display invited/joined status" --> MemberUI["Member Avatar UI"]
  Frontend -- "Fix role name formatting" --> AuthorityUI["Authority Tiles"]
```

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>workspace-role.service.ts</strong><dd><code>Add invitation status to member data</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/workspace-role/workspace-role.service.ts

<ul><li>Add <code>invitationAccepted</code> field to member response object<br> <li> Refactor member mapping to include workspace member invitation status</ul>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/1104/files#diff-5401308ebcabca69186b52b93a1e3c3febadf3da5ed61d2880e797eb5d9fb2aa">+13/-9</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Update schema for invitation status</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

packages/schema/src/workspace-role/index.ts

- Add `invitationAccepted` boolean field to member schema

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/1104/files#diff-fd6fa126715bdcbc710e5a1f2cf2a224d07c32b2a217e4e0ad5414aed87677e2">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Fix member status display and role formatting</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/platform/src/components/roles/roleCard/index.tsx

<ul><li>Fix <code>AuthorityTile</code> to display full role names instead of just first two <br>words<br> <li> Add visual distinction for invited vs joined members with opacity<br> <li> Update tooltip to show "Invited" or "Joined" status<br> <li> Change authority tiles layout from grid to flexbox</ul>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/1104/files#diff-1eac649a2f68d1d91333f9d732e5b48873fb62ed54b9b7b1690ebf421301a8ac">+49/-41</a>&nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

</details>

___

### CODE REVIEW

File: apps/platform/src/components/roles/roleCard/index.tsx [hunk 1]
```diff
@@ -25,13 +25,14 @@ interface RoleListItemProps {
...
+    .split('_')
+    .map((word) => word.charAt(0) + word.slice(1).toLowerCase())
+    .join(' ')
 
   return (
-    <div className="h-fit w-full rounded-md border border-cyan-200 bg-cyan-950 px-2 py-1 text-center text-sm text-cyan-200">
-      {first} {second}
+    <div className="h-fit w-fit rounded-md border border-cyan-200 bg-cyan-950 px-2 py-1 text-center text-sm text-cyan-200">
+      {formattedAuthority}
     </div>
```
Comment (Souvik9205) [inline apps/platform/src/components/roles/roleCard/index.tsx:36]: maybe you can add more padding and in between gap...the screenshot, you have shared looks little overcrowded

Comment (PrasunShrivastav) [reply apps/platform/src/components/roles/roleCard/index.tsx]: i changed it now is it good now or more spacing is needed
image
