### PR TITLE
fix(platform): Added tooltips and disabled deletion of workspace admin in members

### LINKED ISSUE #887: PLATFORM: Inconsistency in members tab resign
## Description

- I shouldn't be able to remove myself from the workspace Image
- Hovering on these should give me a tooltip stating what the button does Image

### PR DESCRIPTION
**Pull request by poswalsameer**
## Description
This PR disables the deletion of workspace admin in the members tab and adds tooltips for a better UX.

Fixes #887 

## Screenshots of relevant screens
Screenshot 2025-04-27 221151
Screenshot 2025-04-27 221159

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
Enhancement

___

### **Description**
- Disabled removal of workspace admin in members table

- Added tooltips for member action buttons

- Improved user experience and clarity in members management

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Disable admin removal and add tooltips to member actions</code>&nbsp; </dd></summary>
<hr>

apps/platform/src/components/members/membersTable/index.tsx

<li>Added logic to detect if a member is a workspace admin<br> <li> Disabled the remove button for admin members<br> <li> Wrapped action buttons (remove, edit, transfer ownership) in tooltips<br> <li> Provided descriptive tooltip messages for each action

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/908/files#diff-195a25e7b5d532c62c6a5b350eee421ca1feed06d35cec64b728866fd02aaae4">+66/-18</a>&nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about Qodo Merge usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

### CODE REVIEW

File: apps/platform/src/components/members/membersTable/index.tsx [hunk 1]
```diff
@@ -39,6 +40,11 @@ function MemberRow({
   onEditMember: (member: GetMembersResponse['items'][number]) => void
   onTransferOwnership: (member: GetMembersResponse['items'][number]) => void
 }) {
+
+  const isAdminRole = member.roles.some(role =>
```
Comment (rajdip-b) [inline apps/platform/src/components/members/membersTable/index.tsx:44]: You should use `useMemo` hook in here

**Review by rajdip-b — CHANGES_REQUESTED** [review]

File: apps/platform/src/components/members/membersTable/index.tsx (hunk 1 above)
Comment (poswalsameer) [reply apps/platform/src/components/members/membersTable/index.tsx:44]: > You should use `useMemo` hook in here

I thought about it, but will it genuinely have some effect here?

Comment (rajdip-b) [reply apps/platform/src/components/members/membersTable/index.tsx:44]: Yes, every time the component reloads, the filter logic will start running. That will slow down the browser

Comment (poswalsameer) [reply apps/platform/src/components/members/membersTable/index.tsx:44]: Sure, I will just add it then.

Comment (poswalsameer) [reply apps/platform/src/components/members/membersTable/index.tsx]: @rajdip-b done

**Review by rajdip-b — APPROVED** [review]
