### PR TITLE
fix(platform): Optimized user update request body

### LINKED ISSUE #604: Editing the name from the settings does not update in the database.
Keyshade-Personal-MicrosoftEdge2025-01-0601-51-05-ezgif com-video-to-gif-converter

### PR DESCRIPTION
**Pull request by omarNaifer12**
## Description
The problem occurred when editing the name, as it triggered an error and did not work in the database.

Fixes #604 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

. The issue was in the updateSelf function, where if the user sent the same email, it would cause a conflict. So, I added a condition to ensure that the email of the user is not the same as the one they sent, and i add this logic too optional to updateUser function so maybe we use it in the future.
And a small edit in ./Vector because it gives an error with lowercase; the file name is not the same.

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
Bug fix

___

### **Description**
- Fixed issue where updating user name failed in database.

- Added condition to prevent email conflict during updates.

- Introduced `NotFoundException` for non-existent users in `updateUser`.

- Corrected file reference case sensitivity in SVG imports.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>user.service.ts</strong><dd><code>Fix user update logic and email conflict handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/user/service/user.service.ts

<li>Added condition to avoid email conflict in <code>updateSelf</code>.<br> <li> Introduced <code>NotFoundException</code> for missing users in <code>updateUser</code>.<br> <li> Enhanced logic to ensure email uniqueness during updates.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/605/files#diff-6ca55e419496e622d41d22930ddd6d7e7d9f907148c36afcae40ef6320dab922">+8/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Fix case sensitivity in SVG file import</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/platform/public/svg/shared/index.ts

- Corrected case sensitivity issue in `Vector.svg` import.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/605/files#diff-b19197cf0cc705221cc0644813c57744bde5dc17c69f2ea75b9e0ea3d324eb6b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by omarNaifer12** [comment]
@rajdip-b ,I refactored the code to the frontend and added a new state to handle the case where the user changes the email input and then reverts to the original email, ensuring that only a different email or null is sent to the backend.

File: apps/platform/src/app/(main)/settings/@profile/page.tsx
Comment (rajdip-b) [inline apps/platform/src/app/(main)/settings/@profile/page.tsx:1]: You should add whitespaces in between names and operators like all the other statements in the file.

**Review by rajdip-b — CHANGES_REQUESTED** [review]
Can you also post a working demo? For both the cases:
- You specify a different email
- You dont specify any email

**Comment by omarNaifer12** [comment]
I just added the missing email in the data of the updateSelf function, so now it works for both options.

Uploading Keyshade - Personal - Microsoft_ Edge 2025-01-08 14-40-48.mp4…

File: apps/api/src/user/service/user.service.ts [hunk 1]
```diff
@@ -45,7 +44,7 @@ export class UserService {
   }
 
   async updateSelf(user: UserWithWorkspace, dto: UpdateUserDto) {
-    const data = {
+    let data : any = {
```
Comment (rajdip-b) [inline apps/api/src/user/service/user.service.ts:47]: If it's not throwing up any lint errors, then its better to leave it untouched. We have a set of types for this, but introducing that to the PR will make it out of scope

**Review by rajdip-b — CHANGES_REQUESTED** [review]

File: apps/api/src/user/service/user.service.ts (hunk 1 above)
Comment (omarNaifer12) [reply apps/api/src/user/service/user.service.ts:47]: I added any because, without it, it threw an error: Property 'email' does not exist on type '{ name: string; profilePictureUrl: string; isOnboardingFinished: boolean; }', because we were missing the email in the function to update. We need data.email = dto.email, or we can include email in data with the condition to be undefined if it is null.

Comment (rajdip-b) [reply apps/api/src/user/service/user.service.ts:47]: `UpdateSelfRequest` from `@keyshade/schema` is what you would need to use in that place then. Because we strictly are against `any` until and unless its that important.

Comment (omarNaifer12) [reply apps/api/src/user/service/user.service.ts:47]: great

**Review by rajdip-b — APPROVED** [review]

**Comment by rajdip-b** [comment]
Exactly! That's the expected result. You see, we don't want people to be able to set their email to anything and everything. Whenever someone tries to update their email, we send an otp to them. Then, once they provide that OTP to us, we update the email. This prevents users to impersonate other users by duping emails.
